import turtle

def drawJieut(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(135)
    turtle.forward(70)
    turtle.right(180)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.left(45)

def drawO(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(180)
    turtle.forward(50)

def drawHieut(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(180)
    turtle.forward(50)
    turtle.penup()
    turtle.right(180)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(40)
    turtle.pendown()
    turtle.left(90)
    turtle.circle(15)

def drawYeo(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(180)
    turtle.forward(50)
    turtle.right(180)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(25)
    turtle.right(180)

def drawNieun(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)

def drawSieut(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right(135)
    turtle.forward(70)
    turtle.right(180)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.left(45)

def drawI(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)

def drawKieuk(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)

drawJieut(-135,50)
drawO(-110,-5)
drawHieut(-25,50)
drawYeo(0,30)
drawNieun(-25,-5)
drawSieut(110,50)
drawI(135,50)
drawKieuk(85,-5)

turtle.exitonclick()